# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/22763f8f-9dc9-47fe-8798-2b36d27933b2";
    fsType = "btrfs";
    options = ["subvol=rootfs"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/CE54-E5B8";
    fsType = "vfat";
  };

  fileSystems."/games" = {
    device = "/dev/disk/by-uuid/22763f8f-9dc9-47fe-8798-2b36d27933b2";
    fsType = "btrfs";
    options = ["subvol=games"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/22763f8f-9dc9-47fe-8798-2b36d27933b2";
    fsType = "btrfs";
    options = ["subvol=home"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/22763f8f-9dc9-47fe-8798-2b36d27933b2";
    fsType = "btrfs";
    options = ["subvol=nix"];
  };

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;

  networking.interfaces.enp16s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp21s0u1u2u1c2.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp17s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
